### ISSUE TITLE
baseline对比实现

### ISSUE THREAD

**Issue by junkangwu** [THUwangcy/DirectAU#6]
感谢贵组的优秀工作，同时在模型对比方面，请问在recbole框架中如何添加负采样方式？因为recbole中BPR都是1-1负采样，请问如果想对比1-N负采样形式代码修改主要是？

**Comment by THUwangcy** [comment]
感谢关注，负采样设定可以参考 RecBole 的 [Training Setting](https://recbole.io/docs/user_guide/config/training_settings.html) 参数。

**Comment by junkangwu** [comment]
好的，但似乎直接更改sample_num参数没有想象中效果,我去问问recbole开发者吧，感谢
