### ISSUE TITLE
关于baseline的运行效果

### ISSUE THREAD

**Issue by love-searcher** [THUwangcy/DirectAU#7]
我在使用您的代码库运行时，LightGCN在Gowalla和Yelp数据集上的效果甚至比BPRMF的还要差一些（BPRMF的效果与您论文中的汇报相当），请问您对实验上有什么建议么？或者可能是什么原因导致的这个问题的出现呢？

**Comment by THUwangcy** [comment]
根据之前的经验，LightGCN 需要设置较小的 weight_decay 会有正常的效果，可以将其设置为 1e-8 甚至 0 试试

**Comment by love-searcher** [comment]
您好：     您的邮件已经收到。                                                     李智源

**Comment by love-searcher** [comment]
非常感谢，目前已能使用LightGCN和几个对比学习算法在Gowalla和Yelp上获得比较好的效果。
但是在DirectAU上的效果还没能达到论文中的水平，暂时在我的训练上略差于对比学习算法SGL和SimGCL，请问有哪些建议来提升效果么？

**Comment by THUwangcy** [comment]
是指结合 LightGCN 的效果达不到论文中的水平吗？README 中结合 MF 的命令应该是可以复现结果的

**Comment by love-searcher** [comment]
好的好的，感谢！
相应的参数我没设置，直接按照DirectAU.yaml中的来了
